version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13-browsers
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn export
      - add_ssh_keys:
          fingerprints:
            - '43:d7:0c:d4:72:e9:b2:a8:c7:fb:0f:c1:f7:a7:c5:f6'
      - deploy:
          name: Deploying to dev
          command: |
            echo "Deploying to dev"
            ssh ubuntu@145.239.89.148 "cd /var/www/dev.landing.rndevs.com && git pull && yarn install && yarn build && yarn export"
