version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13-browsers
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn export
      - add_ssh_keys:
          fingerprints:
            - '43:d7:0c:d4:72:e9:b2:a8:c7:fb:0f:c1:f7:a7:c5:f6'
      - deploy:
          name: Deploy to dev.landing.rndevs.com
          command: |
            rsync -avz --delete-after --exclude=".env*" --exclude=".next" ~/app/out/ ubuntu@145.239.89.148:/var/www/dev.landing.rndevs.com/
