version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-v1-{{ checksum "yarn.lock" }}
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Stop dev.landing.rndevs.com
          command: pm2 stop dev.landing.rndevs.com
      - run:
          name: Delete all available instance
          command: pm2 delete all
      - run:
          name: Start dev.landing.rndevs.com
          command: pm2 start npm --name "dev.landing.rndevs.com" -- start
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
