version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Export
          command: yarn export
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-v1-{{ checksum "yarn.lock" }}
  deploy:
    docker:
      - image: bitnami/ssh:latest
    steps:
      - attach_workspace:
          at: ~/workspace
      - add_ssh_keys:
          fingerprints:
            - '43:d7:0c:d4:72:e9:b2:a8:c7:fb:0f:c1:f7:a7:c5:f6'
      - run:
          name: Copy files to server
          command: |
            ssh root@145.239.89.148 "rm -rf /var/www/html/*"
            scp -r -o "StrictHostKeyChecking no" ~/workspace/out/* root@145.239.89.148:/var/www/html/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
