name: Deploy to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Export application
        run: yarn export

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ubuntu
          remote-host: 145.239.89.148
          remote-port: 22
          local-folder: out/
          remote-folder: /var/www/dev.landing.rndevs.com/
          args: "-rltgoDzvO --delete"
