name: Deploy to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          sudo npm install -g yarn
          yarn install

      - name: Build and export Next.js application
        run: |
          yarn build
          yarn export

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v2.2.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete-after --exclude='.env*' --exclude='.next'"
        with:
          server: ubuntu@145.239.89.148
          remote_path: /var/www/dev.landing.rndevs.com/
          local_path: ./out
          ignore_errors: true
