name: Deploy to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Export application
        run: yarn export

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          REMOTE_USER: ubuntu
          REMOTE_HOST: 145.239.89.148
          REMOTE_PORT: 22
          SOURCE: out/
          TARGET: /var/www/dev.landing.rndevs.com/
          ARGS: "-rltgoDzvOu --delete"
      
      - name: Serve application
        run: yarn serve
